name: pinpin
description: 1037 pinpin.

publish_to: 'none'
version: 0.1.1-beta

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  dio: ^4.0.6
  get: ^4.6.5
  sqflite: ^2.0.3
  floor: ^1.4.1
  path: ^1.8.1
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  loading_more_list: ^4.1.2
  boxy: ^2.0.6+1
  image_picker: ^0.8.6
  flutter_slidable: ^2.0.0
  fluttertoast:
  html: ^0.15.2

  util:
    path: modules/util
  widget:
    path: modules/widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  floor_generator: ^1.4.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_tag/icon_big/
